// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0F92Pgvy8UqMAr-9Zw-lLwb9UKU7KM0',
    appId: '1:798827791843:web:f5cbfea24dde61d2ab4cd6',
    messagingSenderId: '798827791843',
    projectId: 'medical-app-raman-sss',
    authDomain: 'medical-app-raman-sss.firebaseapp.com',
    storageBucket: 'medical-app-raman-sss.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_mRV_hiyjTWKLHOVh8dwRf2vbQO4K9Ag',
    appId: '1:798827791843:android:284096225b083fadab4cd6',
    messagingSenderId: '798827791843',
    projectId: 'medical-app-raman-sss',
    storageBucket: 'medical-app-raman-sss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASBSaJaFwxXJmo2r-jjg1nMmXBi8JDvFk',
    appId: '1:798827791843:ios:15ee3f49efd25710ab4cd6',
    messagingSenderId: '798827791843',
    projectId: 'medical-app-raman-sss',
    storageBucket: 'medical-app-raman-sss.appspot.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASBSaJaFwxXJmo2r-jjg1nMmXBi8JDvFk',
    appId: '1:798827791843:ios:15ee3f49efd25710ab4cd6',
    messagingSenderId: '798827791843',
    projectId: 'medical-app-raman-sss',
    storageBucket: 'medical-app-raman-sss.appspot.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT0F92Pgvy8UqMAr-9Zw-lLwb9UKU7KM0',
    appId: '1:798827791843:web:c02e9836cfc3b6d0ab4cd6',
    messagingSenderId: '798827791843',
    projectId: 'medical-app-raman-sss',
    authDomain: 'medical-app-raman-sss.firebaseapp.com',
    storageBucket: 'medical-app-raman-sss.appspot.com',
  );
}
